name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest tests/

      - name: Train Model and Deploy
        run: |
          python model/train.py
          # Optionally, deploy your model here (e.g., to a cloud service)

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.4.1
        with:
          name: trained-model
          path: model/california_housing_model.pkl

